import * as rds from 'aws-cdk-lib/aws-rds';

export const config = {
  ECR_STACK_ID: 'kaizen-ecr-stack',
  ECR_REPOSITORY_ID: 'kaizen-ecr-repository',
  KAIZEN_STACK_ID: 'kaizen-stack',
  HOSTED_ZONE_ID: 'kaizen-hosted-zone',
  DOMAIN: 'curabu.com',
  CERTIFICATE_ID: 'kaizen-certificate',
  VPC_STACK_ID: 'kaizen-vpc-stack',
  VPC_ID: 'kaizen-vpc',
  VPC_PUBLIC_SUBNET_NAME: 'kaizen-vpc-public-subnet',
  VPC_PRIVATE_SUBNET_NAME: 'kaizen-vpc-private-subnet',
  DATABASE_ENGINE: rds.PostgresEngineVersion.VER_15_4,
  DATABASE_STACK_ID: 'kaizen-db-stack',
  DATABASE_ID: 'kaizen-db',
  DATABASE_NAME: 'kaizen',
  DATABASE_PORT: 5432,
  DATABASE_USERNAME: 'kaizen_db_admin',
  DATABASE_SECRET_ID: 'kaizen-db-secret',
  DATABASE_CREDENTIALS_ID: 'kaizen-db-credentials',
  DATABASE_PARAMETER_GROUP_ID: 'kaizen-db-parameter-group',
  DATABASE_SECURITY_GROUP_ID: 'kaizen-db-security-group',
  DATABASE_SUBNET_GROUP_ID: 'kaizen-db-subnet-group',
  DATABASE_ADDRESS_ID: 'kaizen-db-address',
  API_STACK_ID: 'kaizen-api-stack',
  API_CLUSTER_ID: 'kaizen-api-cluster',
  API_TASK_DEFINITION_ID: 'kaizen-api-task-definition',
  API_CONTAINER_ID: 'kaizen-api-container',
  API_SECURITY_GROUP_ID: 'kaizen-api-security-group',
  API_SCALING_GROUP_CAPACITY_ID: 'kaizen-api-scaling-group-capacity',
  API_SERVICE_ID: 'kaizen-api-service',
  API_LOAD_BALANCER_ID: 'kaizen-api-load-balancer',
  API_TARGET_GROUP_ID: 'kaizen-api-target-group',
  API_HTTPS_LISTENER_ID: 'kaizen-api-https-listener',
  API_HTTP_LISTENER_ID: 'kaizen-api-http-listener',
  API_LOAD_BALANCER_DNS_ID: 'kaizen-api-load-balancer-dns',
  API_LOG_GROUP_ID: 'kaizen-api-log-group',
  API_A_RECORD_ID: 'kaizen-api-a-record',
  API_SUBDOMAIN: 'api.finance',
  FRONTEND_SUBDOMAIN: 'finance',
  FRONTEND_STACK_ID: 'kaizen-frontend-stack',
  FRONTEND_BUCKET_ID: 'kaizen-frontend-bucket',
  FRONTEND_DISTRIBUTION_ID: 'kaizen-frontend-distribution',
  FRONTEND_DISTRIBUTION_URL: 'kaizen-frontend-distribution-url',
  FRONTEND_A_RECORD_ID: 'kaizen-frontend-a-record'
};
