version: '3'
services:
  postgres_test:
    image: postgres:latest
    container_name: kaizen_test_db
    environment:
      POSTGRES_USER: kaizen_api_test
      POSTGRES_PASSWORD: kaizen_api_test_password
      POSTGRES_DB: kaizen_test
    ports:
      - '54321:5432'
