name: Kaizen CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # TODO: We only have one environment for now
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Deploy Docker Image
        run: |
          npm run api:docker:build --aws-repository-id=${{ secrets.AWS_ECR_REPOSITORY_ID }}
          npm run api:docker:tag --aws-repository-id=${{ secrets.AWS_ECR_REPOSITORY_ID }} --aws-account-id=${{ secrets.AWS_ACCOUNT_ID }} --aws-region=${{ secrets.AWS_REGION }}
          npm run api:docker:push --aws-repository-id=${{ secrets.AWS_ECR_REPOSITORY_ID }} --aws-account-id=${{ secrets.AWS_ACCOUNT_ID }} --aws-region=${{ secrets.AWS_REGION }}

      - name: Deploy Infrastructure Changes
        run: |
          cd infrastructure
          npm run stack:build
          npm run stack:deploy
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRATION: ${{ vars.ACCESS_TOKEN_EXPIRATION }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          REFRESH_TOKEN_EXPIRATION: ${{ vars.REFRESH_TOKEN_EXPIRATION }}
          REFRESH_TOKEN_COOKIE_DOMAIN: ${{ vars.REFRESH_TOKEN_COOKIE_DOMAIN }}
          API_PORT: ${{ vars.API_PORT }}
          API_DOMAIN: ${{ vars.API_DOMAIN }}
          FRONTEND_DOMAIN: ${{ vars.FRONTEND_DOMAIN }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DATABASE_SECRET_ID: ${{ secrets.AWS_DATABASE_SECRET_ID }}
          AWS_DATABASE_HOST: ${{ secrets.AWS_DATABASE_HOST }}
          AWS_DATABASE_NAME: ${{ secrets.AWS_DATABASE_NAME }}
          AWS_DATABASE_PORT: ${{ secrets.AWS_DATABASE_PORT }}
          AWS_DATABASE_WHITELIST: ${{ secrets.AWS_DATABASE_WHITELIST }}
