name: Kaizen CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/kaizen-setup.yml

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Set Working Directory
        run: cd kaizen

      - name: Build
        run: |
          cd kaizen 
          npm run build
        continue-on-error: false

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Set Working Directory
        run: cd kaizen

      - name: Lint
        run: npm run lint
        continue-on-error: false

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Set Working Directory
        run: cd kaizen

      - name: Test
        run: cdnpm run test
        continue-on-error: false
