name: Kaizen CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/kaizen-action.yml

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build
        continue-on-error: false

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint
        continue-on-error: false

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: npm run test
        continue-on-error: false
