name: Kaizen CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/kaizen-setup.yml

    steps:
      - name: Build
        run: npm run build
        continue-on-error: false

  lint:
    uses: ./.github/workflows/kaizen-setup.yml

    steps:
      - name: Lint
        run: npm run lint
        continue-on-error: false

  test:
    uses: ./.github/workflows/kaizen-setup.yml

    steps:
      - name: Test
        run: npm run test
        continue-on-error: false
