name: Kaizen CD

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/kaizen-action.yml

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      AWS_ECS_REPOSITORY: kaizen-server-repository

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Push Docker Image
        run: |
          cd apps/api
          npm run docker:build
          npm run docker:tag --region=${{ env.AWS_REGION }} --repository=${{ env.AWS_ECS_REPOSITORY }}
          npm run docker:push --region=${{ env.AWS_REGION }} --repository=${{ env.AWS_ECS_REPOSITORY }}

      - name: Deploy AWS Stack
        run: |
          cd ../../infrastructure
          npm run stack:build
          npm run stack:deploy
